export type UiLanguage = "german" | "finnish" | "swiss" | "french" | "cantonese";
export type Translator = (key: string, values?: Record<string, string | number>) => string;

const de: Record<string, string> = {
  home: "Home", review: "Review", cards: "Karten", progress: "Fortschritt", stats: "Statistiken", settings: "Einstellungen",
  previousLanguage: "Vorherige Sprache", nextLanguage: "Nächste Sprache", playCardAudio: "Kartenaudio abspielen", noCardAudio: "Kein Audio auf dieser Karte", soundOff: "Feedback-Sounds ausschalten", soundOn: "Feedback-Sounds einschalten",
  dueToday: "Heute fällig", allDue: "Alle fälligen Karten", startReview: "Review starten", viewDeck: "Stapel ansehen", yourLanguages: "Deine Sprachen", cardsLearned: "{count} Karten gelernt",
  learningActivity: "Lernaktivität", fewer: "Weniger", more: "Mehr", week: "Woche", month: "Monat", year: "Jahr", days: "Tage", day: "Tag",
  progressPath: "Fortschrittsweg", languageJourney: "Deine Sprachreise", eachCard: "Jede gelernte Karte bringt dich zum nächsten Meilenstein.", yourLevel: "Dein Level",
  cardsUntil: "Noch {count} gelernte Karten bis {level}.", highestLevel: "Du hast den höchsten Meilenstein erreicht.", continueLearning: "Weiterlernen", learned: "gelernt", inDeck: "im Stapel",
  milestoneStart: "Start", milestoneFoundations: "Grundlagen", milestoneBasis: "Basis", milestoneIndependent: "Selbstständig", milestoneConfident: "Sicher", milestoneAdvanced: "Fortgeschritten", milestoneMastery: "Sehr sicher",
  milestone0: "Erste Wörter und Laute", milestone1: "Einfache Alltagssituationen", milestone2: "Kurze Gespräche verstehen", milestone3: "Über vertraute Themen sprechen", milestone4: "Spontan und detailliert kommunizieren", milestone5: "Komplexe Inhalte flexibel nutzen", milestone6: "Nahezu mühelos verstehen",
  overview: "Übersicht", currentStreak: "Aktueller Streak", reviewsPeriod: "Reviews im Zeitraum", activeDays: "aktive Tage", freezeReady: "Freeze bereit", freezesReady: "Freezes bereit", lastWeek: "Diese Woche", lastMonth: "Die letzten fünf Wochen", lastYear: "Die letzten zwölf Monate",
  chooseReview: "Was möchtest du heute lernen?", endReview: "Review beenden", undo: "Zurück", undoLastReview: "Letzte Bewertung rückgängig", preparing: "Anki bereitet deine Karten vor …", loadingDeck: "Der aktive Sprachstapel wird geladen.", connectionLost: "Verbindung kurz unterbrochen", retry: "Erneut versuchen",
  nothingDue: "Hier ist gerade nichts fällig.", emptyDeck: "{language} ist in Anki noch leer oder für heute bereits erledigt.", backOverview: "Zurück zur Übersicht", finished: "Für heute geschafft.", completed: "Du hast {count} Karten in {language} mit Anki wiederholt.", showAnswer: "Antwort zeigen",
  again: "Nochmal", hard: "Schwer", good: "Gut", easy: "Leicht", yourAnswer: "Deine Antwort", typeAnswer: "Antwort eintippen …", yourInput: "Deine Eingabe", correctAnswer: "Richtige Antwort", answerCorrect: "Richtig", answerDifference: "Antwortvergleich", noInput: "Keine Eingabe", reviewMilestoneTitle: "Starke Runde!", reviewMilestoneBody: "Kurze Pause verdient – du bist im Rhythmus.", milestoneCards: "{count} Karten geschafft", keepGoing: "Weiter geht’s", answer: "Antwort", meaning: "Bedeutung", examples: "Beispiele", pronunciation: "Aussprache", mainDeck: "Hauptstapel",
  record: "Aufnehmen", openingMic: "Mikrofon wird geöffnet …", stopRecording: "Stoppen", playMine: "Meine Aufnahme", playSolution: "Lösung anhören", recording: "Aufnahme läuft", micUnavailable: "Mikrofon ist nicht verfügbar.", micDenied: "Mikrofonzugriff wurde nicht erlaubt.", rerecord: "Neu aufnehmen",
  cardCollection: "Kartensammlung", languageDecks: "Deine Sprachstapel", ankiLocal: "Alle Karten bleiben in Anki – hier lernst und überblickst du sie.", active: "Aktiv", languageDeck: "Sprachstapel", cardsTotal: "Karten gesamt", subdecks: "Unterstapel", noCards: "Noch keine Karten vorhanden", moreItems: "+ {count} weitere", details: "Details", learn: "Lernen", view: "Ansehen",
  learningOverview: "Lernübersicht", todayStatus: "Dein heutiger Stand", liveAnki: "Live aus deiner lokalen Anki-Sammlung.", answeredToday: "heute beantwortet", cardsOverall: "Karten insgesamt", dueByLanguage: "Fällige Karten nach Sprache", languageDecksCount: "{count} Sprachstapel",
  appSettings: "App-Einstellungen", learningExperience: "Lernerlebnis", settingsLocal: "Die Einstellungen werden lokal auf diesem Computer gespeichert.", pleasantSounds: "Angenehme Feedback-Sounds", pleasantSoundsDetail: "Kurze Töne beim Aufdecken und Bewerten.", autoplay: "Kartenaudio automatisch abspielen", autoplayDetail: "Spielt vorhandenes Anki-Audio beim Kartenwechsel ab.", reduceMotion: "Bewegungen reduzieren", reduceMotionDetail: "Deaktiviert Karten- und Erfolgsanimationen.", immersiveUi: "App in der Zielsprache", immersiveUiDetail: "Übersetzt die gesamte Bedienoberfläche in die aktive Sprache.", ankiConnection: "Anki-Verbindung", connected: "Anki ist lokal erreichbar. Wiederholungen und Intervalle werden synchron verarbeitet.", checking: "Verbindung wird geprüft …", disconnected: "Anki ist nicht erreichbar.", reconnect: "Neu prüfen",
  cardBrowser: "Kartenbrowser", browserSubtitle: "Durchsuche Karten, Notizen, Felder und Anki-Suchbegriffe.", openInAnki: "In Anki öffnen", searchCards: "Karten, Inhalte oder Anki-Suche …", notes: "Notizen", all: "Alle", due: "Fällig", newCards: "Neu", suspended: "Ausgesetzt", searching: "Suche …", results: "{count} Ergebnisse", showingFirst: "Die ersten {count} werden angezeigt", allShown: "Alle angezeigt", searchError: "Suche nicht möglich", noResults: "Nichts gefunden", trySearch: "Versuche einen anderen Begriff oder Filter.", emptyCard: "Leere Karte", cardDetails: "Kartendetails", noteDetails: "Notizdetails", editInAnki: "In Anki bearbeiten", interval: "Intervall", reviews: "Wiederholungen", lapses: "Fehler", noTags: "Keine Tags", emptyField: "Leeres Feld", selectResult: "Wähle links ein Ergebnis aus.",
  ankiStatistics: "Anki-Statistiken", learnedCards: "gelernte Karten", averageActiveDay: "Ø pro aktivem Tag", reviewsLast30: "Wiederholungen · 30 Tage", reviewChartSubtitle: "Deine tatsächliche Anki-Aktivität", collectionStructure: "Sammlungsstruktur", learning: "Lernen", young: "Jung", mature: "Reif", autoSync: "Automatisch mit AnkiWeb synchronisieren", autoSyncDetail: "Synchronisiert wenige Sekunden nach einer Bewertung.", darkMode: "Dunkelmodus", darkModeDetail: "Folgt automatisch der Systemeinstellung dieses Computers.", system: "System", ankiWebSync: "AnkiWeb-Synchronisierung", syncing: "Anki und AnkiWeb werden synchronisiert …", syncComplete: "Synchronisierung abgeschlossen.", syncFailed: "Synchronisierung fehlgeschlagen.", syncReady: "Manuell synchronisieren oder automatische Synchronisierung verwenden.", syncNow: "Jetzt synchronisieren",
  translateType: "Übersetzen & eintippen", speakTranslate: "Sprechen & übersetzen", readUnderstand: "Lesen & verstehen", listening: "Hörverstehen", verbs: "Verben", phonetics: "Aussprache", sounds: "Laute & Aussprache", characters: "Schriftzeichen", mnemonic: "Merksatz", enterJyutping: "Jyutping eingeben", frenchAnswer: "Französische Antwort", withArticle: "Mit Artikel", phoneme: "Phonem",
};

const fr: Record<string, string> = {
  home: "Accueil", review: "Révision", cards: "Cartes", progress: "Progrès", stats: "Statistiques", settings: "Réglages",
  previousLanguage: "Langue précédente", nextLanguage: "Langue suivante", playCardAudio: "Lire l’audio de la carte", noCardAudio: "Aucun audio sur cette carte", soundOff: "Désactiver les sons", soundOn: "Activer les sons",
  dueToday: "À réviser aujourd’hui", allDue: "Toutes les cartes à réviser", startReview: "Commencer", viewDeck: "Voir le paquet", yourLanguages: "Tes langues", cardsLearned: "{count} cartes apprises",
  learningActivity: "Activité d’apprentissage", fewer: "Moins", more: "Plus", week: "Semaine", month: "Mois", year: "Année", days: "jours", day: "jour",
  progressPath: "Parcours de progrès", languageJourney: "Ton parcours linguistique", eachCard: "Chaque carte apprise te rapproche du prochain jalon.", yourLevel: "Ton niveau", cardsUntil: "Encore {count} cartes apprises avant {level}.", highestLevel: "Tu as atteint le jalon le plus élevé.", continueLearning: "Continuer", learned: "apprises", inDeck: "dans le paquet",
  milestoneStart: "Départ", milestoneFoundations: "Fondations", milestoneBasis: "Bases", milestoneIndependent: "Autonome", milestoneConfident: "À l’aise", milestoneAdvanced: "Avancé", milestoneMastery: "Maîtrise", milestone0: "Premiers mots et sons", milestone1: "Situations simples du quotidien", milestone2: "Comprendre de courtes conversations", milestone3: "Parler de sujets familiers", milestone4: "Communiquer spontanément et en détail", milestone5: "Utiliser avec souplesse des contenus complexes", milestone6: "Comprendre presque sans effort",
  overview: "Aperçu", currentStreak: "Série actuelle", reviewsPeriod: "Révisions sur la période", activeDays: "jours actifs", freezeReady: "gel disponible", freezesReady: "gels disponibles", lastWeek: "Cette semaine", lastMonth: "Les cinq dernières semaines", lastYear: "Les douze derniers mois",
  chooseReview: "Que veux-tu apprendre aujourd’hui ?", endReview: "Quitter la révision", undo: "Retour", undoLastReview: "Annuler la dernière évaluation", preparing: "Anki prépare tes cartes…", loadingDeck: "Le paquet actif est en cours de chargement.", connectionLost: "Connexion momentanément interrompue", retry: "Réessayer", nothingDue: "Rien à réviser pour le moment.", emptyDeck: "{language} est encore vide dans Anki ou déjà terminé pour aujourd’hui.", backOverview: "Retour à l’accueil", finished: "Terminé pour aujourd’hui.", completed: "Tu as révisé {count} cartes en {language} avec Anki.", showAnswer: "Afficher la réponse",
  again: "À revoir", hard: "Difficile", good: "Bien", easy: "Facile", yourAnswer: "Ta réponse", typeAnswer: "Saisis ta réponse…", yourInput: "Ta saisie", correctAnswer: "Réponse correcte", answerCorrect: "Correct", answerDifference: "Comparaison", noInput: "Aucune saisie", reviewMilestoneTitle: "Belle série !", reviewMilestoneBody: "Tu mérites une courte pause — tu es bien lancé.", milestoneCards: "{count} cartes terminées", keepGoing: "Continuer", answer: "Réponse", meaning: "Sens", examples: "Exemples", pronunciation: "Prononciation", mainDeck: "Paquet principal",
  record: "Enregistrer", openingMic: "Ouverture du microphone…", stopRecording: "Arrêter", playMine: "Mon enregistrement", playSolution: "Écouter la solution", recording: "Enregistrement en cours", micUnavailable: "Le microphone n’est pas disponible.", micDenied: "L’accès au microphone n’a pas été autorisé.", rerecord: "Réenregistrer",
  cardCollection: "Collection de cartes", languageDecks: "Tes paquets de langues", ankiLocal: "Toutes les cartes restent dans Anki : apprends-les et consulte-les ici.", active: "Actif", languageDeck: "Paquet de langue", cardsTotal: "Total des cartes", subdecks: "Sous-paquets", noCards: "Aucune carte pour le moment", moreItems: "+ {count} autres", details: "Détails", learn: "Apprendre", view: "Voir",
  learningOverview: "Aperçu d’apprentissage", todayStatus: "Ta progression aujourd’hui", liveAnki: "Données en direct de ta collection Anki locale.", answeredToday: "répondues aujourd’hui", cardsOverall: "cartes au total", dueByLanguage: "Cartes à réviser par langue", languageDecksCount: "{count} paquets de langues",
  appSettings: "Réglages de l’app", learningExperience: "Expérience d’apprentissage", settingsLocal: "Les réglages sont enregistrés localement sur cet ordinateur.", pleasantSounds: "Sons de retour agréables", pleasantSoundsDetail: "De courts sons lors de l’affichage et de l’évaluation.", autoplay: "Lire automatiquement l’audio", autoplayDetail: "Lit l’audio Anki disponible à chaque nouvelle carte.", reduceMotion: "Réduire les animations", reduceMotionDetail: "Désactive les animations des cartes et des réussites.", immersiveUi: "App dans la langue cible", immersiveUiDetail: "Traduit toute l’interface dans la langue active.", ankiConnection: "Connexion Anki", connected: "Anki est accessible localement. Les révisions et intervalles sont synchronisés.", checking: "Vérification de la connexion…", disconnected: "Anki n’est pas accessible.", reconnect: "Vérifier",
  cardBrowser: "Navigateur de cartes", browserSubtitle: "Recherche dans les cartes, notes, champs et requêtes Anki.", openInAnki: "Ouvrir dans Anki", searchCards: "Cartes, contenu ou recherche Anki…", notes: "Notes", all: "Tout", due: "À réviser", newCards: "Nouvelles", suspended: "Suspendues", searching: "Recherche…", results: "{count} résultats", showingFirst: "Les {count} premiers sont affichés", allShown: "Tout est affiché", searchError: "Recherche impossible", noResults: "Aucun résultat", trySearch: "Essaie un autre terme ou filtre.", emptyCard: "Carte vide", cardDetails: "Détails de la carte", noteDetails: "Détails de la note", editInAnki: "Modifier dans Anki", interval: "Intervalle", reviews: "Révisions", lapses: "Oublis", noTags: "Aucun tag", emptyField: "Champ vide", selectResult: "Sélectionne un résultat à gauche.",
  ankiStatistics: "Statistiques Anki", learnedCards: "cartes apprises", averageActiveDay: "moy. par jour actif", reviewsLast30: "Révisions · 30 jours", reviewChartSubtitle: "Ton activité Anki réelle", collectionStructure: "Structure de la collection", learning: "Apprentissage", young: "Jeunes", mature: "Matures", autoSync: "Synchroniser automatiquement avec AnkiWeb", autoSyncDetail: "Synchronise quelques secondes après une évaluation.", darkMode: "Mode sombre", darkModeDetail: "Suit automatiquement le réglage système de cet ordinateur.", system: "Système", ankiWebSync: "Synchronisation AnkiWeb", syncing: "Synchronisation d’Anki avec AnkiWeb…", syncComplete: "Synchronisation terminée.", syncFailed: "Échec de la synchronisation.", syncReady: "Synchronise manuellement ou utilise la synchronisation automatique.", syncNow: "Synchroniser",
  translateType: "Traduire et saisir", speakTranslate: "Parler et traduire", readUnderstand: "Lire et comprendre", listening: "Compréhension orale", verbs: "Verbes", phonetics: "Prononciation", sounds: "Sons et prononciation", characters: "Caractères", mnemonic: "Phrase mnémotechnique", enterJyutping: "Saisir le jyutping", frenchAnswer: "Réponse française", withArticle: "Avec l’article", phoneme: "Phonème",
};

const yue: Record<string, string> = {
  home: "Zyu2 jip6", review: "Wan1 zaap6", cards: "Kaa1 pin2", progress: "Zeon3 dou6", stats: "Tung2 gai3", settings: "Cit3 ding6",
  previousLanguage: "Soeng6 jat1 zung2 jyu5 jin4", nextLanguage: "Haa6 jat1 zung2 jyu5 jin4", playCardAudio: "Biu2 kaa1 pin2 jam1 pan4", noCardAudio: "Ni1 zoeng1 kaa1 pin2 mou5 jam1 pan4", soundOff: "Gwaan1 bai3 tai4 si6 seng1", soundOn: "Hoi1 kai2 tai4 si6 seng1",
  dueToday: "Gam1 jat6 jiu3 wan1", allDue: "So2 jau5 dou3 kei4 kaa1 pin2", startReview: "Hoi1 ci2 wan1 zaap6", viewDeck: "Tai2 paai4 zou2", yourLanguages: "Nei5 ge3 jyu5 jin4", cardsLearned: "Ji5 hok6 {count} zoeng1 kaa1",
  learningActivity: "Hok6 zaap6 wut6 dung6", fewer: "Siu2", more: "Do1", week: "Sing1 kei4", month: "Jyut6", year: "Nin4", days: "jat6", day: "jat6",
  progressPath: "Zeon3 dou6 lou6 sin3", languageJourney: "Nei5 ge3 jyu5 jin4 leoi5 cing4", eachCard: "Mui5 hok6 jat1 zoeng1 kaa1, dou1 wui5 gan6 jat1 bou6 lei5 cing4 bei1.", yourLevel: "Nei5 ge3 kap1 bit6", cardsUntil: "Zung6 caa1 {count} zoeng1 dou3 {level}.", highestLevel: "Nei5 ji5 ging1 dou3 zoei3 gou1 lei5 cing4 bei1.", continueLearning: "Gai3 zuk6 hok6", learned: "ji5 hok6", inDeck: "hai2 paai4 zou2",
  milestoneStart: "Hoi1 ci2", milestoneFoundations: "Gei1 co2", milestoneBasis: "Co1 gaai1", milestoneIndependent: "Duk6 lap6", milestoneConfident: "Suk6 lin6", milestoneAdvanced: "Zeon3 gaai1", milestoneMastery: "Zing1 tung1", milestone0: "Zeoi3 co1 ge3 ci4 jyu5 tung4 seng1 jam1", milestone1: "Gaan2 daan1 jat6 soeng4 cing4 ging2", milestone2: "Ming4 baak6 dyun2 deoi3 waa6", milestone3: "Gong2 suk6 sik1 ge3 waa6 tai4", milestone4: "Zi6 jin4 tung4 coeng4 sai3 gam2 kau1 tung1", milestone5: "Ling4 wut6 wan6 jung6 fuk1 zaap6 noi6 jung4", milestone6: "Gei1 fu4 mou5 mat1 fai3 lik6 gam2 lei5 gaai2",
  overview: "Zung2 laam5", currentStreak: "Jin6 si4 lin4 zuk6 gei2 luk6", reviewsPeriod: "Kei4 gaan1 wan1 zaap6 ci3 sou3", activeDays: "Wut6 joek6 jat6 sou3", freezeReady: "Bou2 wu6 ji5 zing2 hou2", freezesReady: "Bou2 wu6 ji5 zing2 hou2", lastWeek: "Gam1 go3 sing1 kei4", lastMonth: "Zoei3 gan6 ng5 go3 sing1 kei4", lastYear: "Zoei3 gan6 sap6 ji6 go3 jyut6",
  chooseReview: "Gam1 jat6 soeng2 hok6 mat1 je5?", endReview: "Lei4 hoi1 wan1 zaap6", undo: "Faan1 tau4", undoLastReview: "Ceot3 siu1 soeng6 jat1 ci3 ping4 fan1", preparing: "Anki zing3 zoi6 zing2 gan2 kaa1 pin2…", loadingDeck: "Zing3 zoi6 zong1 zoi3 jin6 si4 jyu5 jin4 paai4 zou2.", connectionLost: "Lin4 sin3 zaam6 si4 zung1 dyun6", retry: "Zoi3 si3", nothingDue: "Jin6 zoi6 mou5 kaa1 pin2 dou3 kei4.", emptyDeck: "{language} hai2 Anki zung6 hai6 hung1 ge3, waak6 ze2 gam1 jat6 ji5 ging1 jyun4 sing4.", backOverview: "Faan1 heoi3 zung2 laam5", finished: "Gam1 jat6 gaau2 dim6.", completed: "Nei5 ji5 ging1 jung6 Anki wan1 zaap6 zo2 {count} zoeng1 {language} kaa1 pin2.", showAnswer: "Hin2 si6 daap3 on3",
  again: "Zoi3 lei4", hard: "Kwan3 naan4", good: "Hou2", easy: "Jung4 ji6", yourAnswer: "Nei5 ge3 daap3 on3", typeAnswer: "Jap6 daap3 on3…", yourInput: "Nei5 jap6 ge3 noi6 jung4", correctAnswer: "Zing3 kok3 daap3 on3", answerCorrect: "Zing3 kok3", answerDifference: "Daap3 on3 deoi3 ziu3", noInput: "Mou5 jap6 noi6 jung4", reviewMilestoneTitle: "Hou2 sai2!", reviewMilestoneBody: "Nei5 ji5 ging1 jap6 zo2 zit3 zau3, jau1 sik1 jat1 haa5 laa1.", milestoneCards: "Ji5 jyun4 sing4 {count} zoeng1", keepGoing: "Gai3 zuk6", answer: "Daap3 on3", meaning: "Ji3 si1", examples: "Lai6 geoi3", pronunciation: "Faat3 jam1", mainDeck: "Zyu2 paai4 zou2",
  record: "Luk6 jam1", openingMic: "Zing3 zoi6 hoi1 mai1 hak1 fung1…", stopRecording: "Ting4 zi2", playMine: "Biu2 ngo5 ge3 luk6 jam1", playSolution: "Teng1 biu1 zeon2 daap3 on3", recording: "Luk6 jam1 zung1", micUnavailable: "Mei6 nang4 si2 jung6 mai1 hak1 fung1.", micDenied: "Mei6 wok6 zeon2 si2 jung6 mai1 hak1 fung1.", rerecord: "Zung6 san1 luk6 jam1",
  cardCollection: "Kaa1 pin2 sau1 zong6", languageDecks: "Nei5 ge3 jyu5 jin4 paai4 zou2", ankiLocal: "So2 jau5 kaa1 pin2 dou1 lau4 hai2 Anki; nei5 ho2 ji5 hai2 ni1 dou6 hok6 tung4 tai2.", active: "Si2 jung6 zung1", languageDeck: "Jyu5 jin4 paai4 zou2", cardsTotal: "Kaa1 pin2 zung2 sou3", subdecks: "Zi2 paai4 zou2", noCards: "Zaan6 si4 mou5 kaa1 pin2", moreItems: "+ ling6 ngoi6 {count} go3", details: "Coeng4 sai3", learn: "Hok6 zaap6", view: "Tai2",
  learningOverview: "Hok6 zaap6 zung2 laam5", todayStatus: "Gam1 jat6 zeon3 dou6", liveAnki: "Lei4 zi6 bun2 gei1 Anki sau1 zong6 ge3 zik6 si4 zi1 liu6.", answeredToday: "Gam1 jat6 ji5 daap3", cardsOverall: "Kaa1 pin2 zung2 sou3", dueByLanguage: "Gok3 jyu5 jin4 dou3 kei4 kaa1 pin2", languageDecksCount: "{count} go3 jyu5 jin4 paai4 zou2",
  appSettings: "Jing3 jung6 cing4 sik1 cit3 ding6", learningExperience: "Hok6 zaap6 tai2 jim6", settingsLocal: "Cit3 ding6 zi2 wui5 cyu5 hai2 ni1 bou6 din6 nou5.", pleasantSounds: "Syu1 fuk6 tai4 si6 seng1", pleasantSoundsDetail: "Hin2 si6 daap3 on3 tung4 ping4 fan1 si4 biu2 dyun2 tai4 si6 seng1.", autoplay: "Zi6 dung6 biu2 kaa1 pin2 jam1 pan4", autoplayDetail: "Zyun2 kaa1 si4 zi6 dung6 biu2 Anki jam1 pan4.", reduceMotion: "Gaam2 siu2 dung6 waa2", reduceMotionDetail: "Ting4 jung6 kaa1 pin2 tung4 sing4 gung1 dung6 waa2.", immersiveUi: "Jung6 mok6 biu1 jyu5 jin4 hin2 si6", immersiveUiDetail: "Zoeng1 zing2 go3 gaai3 min6 zyun2 wai4 jin6 si4 jyu5 jin4.", ankiConnection: "Anki lin4 sin3", connected: "Ji5 lin4 zip3 bun2 gei1 Anki; wan1 zaap6 tung4 gaan3 gaak3 wui5 tung4 bou6.", checking: "Zing3 zoi6 gim2 caa4 lin4 sin3…", disconnected: "Mei6 nang4 lin4 zip3 Anki.", reconnect: "Zoi3 gim2 caa4",
  cardBrowser: "Kaa1 pin2 tau3 laam5 hei3", browserSubtitle: "Sau2 cam4 kaa1 pin2, zeoi3 gei3, ling4 wik6 tung4 Anki sau2 cam4 jyu5.", openInAnki: "Hai2 Anki hoi1", searchCards: "Kaa1 pin2, noi6 jung4 waak6 Anki sau2 cam4…", notes: "Zeoi3 gei3", all: "Cyun4 bou6", due: "Dou3 kei4", newCards: "San1", suspended: "Zaam6 ting4", searching: "Sau2 cam4 zung1…", results: "{count} go3 git3 gwo2", showingFirst: "Hin2 si6 tau4 {count} go3", allShown: "Ji5 cyun4 bou6 hin2 si6", searchError: "Mou5 faat3 sau2 cam4", noResults: "Mou5 git3 gwo2", trySearch: "Si3 haa5 ling6 jat1 go3 ci4 waak6 gwo3 leoi6.", emptyCard: "Hung1 kaa1 pin2", cardDetails: "Kaa1 pin2 coeng4 sai3", noteDetails: "Zeoi3 gei3 coeng4 sai3", editInAnki: "Hai2 Anki sau1 gai2", interval: "Gaan3 gaak3", reviews: "Wan1 zaap6", lapses: "Co3 ng6", noTags: "Mou5 biu1 cim1", emptyField: "Hung1 ling4 wik6", selectResult: "Hai2 zo2 bin1 syun2 jat1 go3 git3 gwo2.",
  ankiStatistics: "Anki tung2 gai3", learnedCards: "Ji5 hok6 kaa1 pin2", averageActiveDay: "Mui5 wut6 joek6 jat6 ping4 gwan1", reviewsLast30: "Wan1 zaap6 · 30 jat6", reviewChartSubtitle: "Nei5 ge3 zan1 sat6 Anki wut6 dung6", collectionStructure: "Sau1 zong6 git3 kau3", learning: "Hok6 zaap6 zung1", young: "Nin4 hing1", mature: "Sing4 suk6", autoSync: "Zi6 dung6 tung4 AnkiWeb tung4 bou6", autoSyncDetail: "Ping4 fan1 gei2 miu5 hau6 zi6 dung6 tung4 bou6.", darkMode: "Am3 sik1 mou4 sik1", darkModeDetail: "Zi6 dung6 ceoi4 ni1 bou6 din6 nou5 ge3 hai6 tung2 cit3 ding6.", system: "Hai6 tung2", ankiWebSync: "AnkiWeb tung4 bou6", syncing: "Anki tung4 AnkiWeb zing3 zoi6 tung4 bou6…", syncComplete: "Tung4 bou6 jyun4 sing4.", syncFailed: "Tung4 bou6 sat1 baai6.", syncReady: "Sau2 dung6 tung4 bou6 waak6 si2 jung6 zi6 dung6 tung4 bou6.", syncNow: "Jin6 zoi6 tung4 bou6",
  translateType: "Faan1 jik6 tung4 jap6", speakTranslate: "Gong2 ceot1 tung4 faan1 jik6", readUnderstand: "Jyut6 duk6 lei5 gaai2", listening: "Teng1 lik6 lei5 gaai2", verbs: "Dung6 ci4", phonetics: "Faat3 jam1", sounds: "Seng1 jam1 tung4 faat3 jam1", characters: "Hon3 zi6", mnemonic: "Gei3 jik1 tai4 si6", enterJyutping: "Jap6 Jyutping", frenchAnswer: "Faat3 man4 daap3 on3", withArticle: "Lin4 gun3 ci4", phoneme: "Jam1 wai6",
};

const gsw: Record<string, string> = {
  home: "Dihei", review: "Wiederhole", cards: "Charte", progress: "Fortschritt", stats: "Statistik", settings: "Iistellige",
  previousLanguage: "Vorherigi Sprach", nextLanguage: "Nöchsti Sprach", playCardAudio: "Chartenaudio abspiele", noCardAudio: "Uf dere Charte git’s kei Audio", soundOff: "Feedback-Tön usschalte", soundOn: "Feedback-Tön iischalte",
  dueToday: "Hüt fällig", allDue: "Alli fällige Charte", startReview: "Wiederholig starte", viewDeck: "Stapel aluege", yourLanguages: "Dini Sprache", cardsLearned: "{count} Charte glärnt",
  learningActivity: "Lernaktivität", fewer: "Weniger", more: "Meh", week: "Wuche", month: "Monet", year: "Jahr", days: "Täg", day: "Tag",
  progressPath: "Fortschrittswäg", languageJourney: "Dini Sprachreis", eachCard: "Jedi glärnti Charte bringt di zum nöchste Meilestei.", yourLevel: "Dis Level", cardsUntil: "No {count} glärnti Charte bis {level}.", highestLevel: "Du hesch de höchschti Meilestei erreicht.", continueLearning: "Wiiterlerne", learned: "glärnt", inDeck: "im Stapel",
  milestoneStart: "Start", milestoneFoundations: "Grundlage", milestoneBasis: "Basis", milestoneIndependent: "Selbständig", milestoneConfident: "Sicher", milestoneAdvanced: "Fortgschritte", milestoneMastery: "Sehr sicher", milestone0: "Erschti Wörter und Lüüt", milestone1: "Eifachi Alltagssituatione", milestone2: "Churzi Gspröch verstah", milestone3: "Über vertrauti Theme rede", milestone4: "Spontan und genau kommuniziere", milestone5: "Komplexi Inhalt flexibel bruuche", milestone6: "Fascht mühelos verstah",
  overview: "Übersicht", currentStreak: "Aktuelli Serie", reviewsPeriod: "Wiederholige im Ziitruum", activeDays: "aktivi Täg", freezeReady: "Freeze parat", freezesReady: "Freezes parat", lastWeek: "Die Wuche", lastMonth: "Die letschte füf Wuche", lastYear: "Die letschte zwölf Monet",
  chooseReview: "Was wetsch hüt lerne?", endReview: "Wiederholig beände", undo: "Zrugg", undoLastReview: "Letschti Bewertig rückgängig mache", preparing: "Anki macht dini Charte parat…", loadingDeck: "De aktivi Sprachstapel wird glade.", connectionLost: "D Verbindig isch churz unterbroche", retry: "Nomol probiere", nothingDue: "Da isch grad nüt fällig.", emptyDeck: "{language} isch in Anki no leer oder für hüt scho fertig.", backOverview: "Zrugg zur Übersicht", finished: "Für hüt gschafft.", completed: "Du hesch {count} Charte in {language} mit Anki wiederholt.", showAnswer: "Antwort zeige",
  again: "Nomol", hard: "Schwer", good: "Guet", easy: "Eifach", yourAnswer: "Dini Antwort", typeAnswer: "Antwort iitippe…", yourInput: "Dini Iigab", correctAnswer: "Richtigi Antwort", answerCorrect: "Richtig", answerDifference: "Antwortvergliich", noInput: "Nüt iigäh", reviewMilestoneTitle: "Starchi Rundi!", reviewMilestoneBody: "E churzi Pause hesch der verdient – du bisch voll im Rhythmus.", milestoneCards: "{count} Charte gschafft", keepGoing: "Wiiter gaht’s", answer: "Antwort", meaning: "Bedütig", examples: "Biispiel", pronunciation: "Ussproch", mainDeck: "Hauptstapel",
  record: "Ufnäh", openingMic: "Mikrofon wird ufmacht …", stopRecording: "Stoppe", playMine: "Mini Ufnahm", playSolution: "Lösig lose", recording: "Ufnahm lauft", micUnavailable: "S Mikrofon isch nöd verfügbar.", micDenied: "De Mikrofonzugriff isch nöd erlaubt.", rerecord: "Neu ufnäh",
  cardCollection: "Chartesammlig", languageDecks: "Dini Sprachstapel", ankiLocal: "Alli Charte bliibed in Anki – da lernsch und überblicksch sie.", active: "Aktiv", languageDeck: "Sprachstapel", cardsTotal: "Charte total", subdecks: "Unterstapel", noCards: "No kei Charte vorhande", moreItems: "+ {count} wiiteri", details: "Details", learn: "Lerne", view: "Aluege",
  learningOverview: "Lernübersicht", todayStatus: "Din hütige Stand", liveAnki: "Live us diner lokale Anki-Sammlig.", answeredToday: "hüt beantwortet", cardsOverall: "Charte insgesamt", dueByLanguage: "Fälligi Charte pro Sprach", languageDecksCount: "{count} Sprachstapel",
  appSettings: "App-Iistellige", learningExperience: "Lernerlebnis", settingsLocal: "D Iistellige werded lokal uf däm Computer gspeicheret.", pleasantSounds: "Aagnähmi Feedback-Tön", pleasantSoundsDetail: "Churzi Tön bim Ufdecke und Bewärte.", autoplay: "Chartenaudio automatisch abspiele", autoplayDetail: "Spilt vorhandes Anki-Audio bim Chartewächsel ab.", reduceMotion: "Bewegige reduziere", reduceMotionDetail: "Schaltet Charte- und Erfolgsanimatione us.", immersiveUi: "App i de Zielsproch", immersiveUiDetail: "Übersetzt d ganz Bedienoberflächi i d aktivi Sprach.", ankiConnection: "Anki-Verbindig", connected: "Anki isch lokal erreichbar. Wiederholige und Intervall werded synchron verarbeitet.", checking: "Verbindig wird prüeft…", disconnected: "Anki isch nöd erreichbar.", reconnect: "Neu prüefe",
  cardBrowser: "Charte-Browser", browserSubtitle: "Durchsuech Charte, Notize, Fälder und Anki-Suechbegriffe.", openInAnki: "In Anki ufmache", searchCards: "Charte, Inhalt oder Anki-Suechi …", notes: "Notize", all: "Alli", due: "Fällig", newCards: "Neu", suspended: "Ussetzt", searching: "Sueche …", results: "{count} Ergebnis", showingFirst: "Die erschte {count} werded zeigt", allShown: "Alli zeigt", searchError: "Suechi nöd möglich", noResults: "Nüt gfunde", trySearch: "Probier en andere Begriff oder Filter.", emptyCard: "Leeri Charte", cardDetails: "Chartedetails", noteDetails: "Notizdetails", editInAnki: "In Anki bearbeite", interval: "Intervall", reviews: "Wiederholige", lapses: "Fehler", noTags: "Kei Tags", emptyField: "Leers Fäld", selectResult: "Wähl links es Ergebnis us.",
  ankiStatistics: "Anki-Statistik", learnedCards: "glärnti Charte", averageActiveDay: "Ø pro aktivem Tag", reviewsLast30: "Wiederholige · 30 Täg", reviewChartSubtitle: "Dini tatsächligi Anki-Aktivität", collectionStructure: "Sammligsstruktur", learning: "Am Lerne", young: "Jung", mature: "Riif", autoSync: "Automatisch mit AnkiWeb synchronisiere", autoSyncDetail: "Synchronisiert es paar Sekunde nach ere Bewertig.", darkMode: "Dunkelmodus", darkModeDetail: "Folgt automatisch de System-Iistellig vo däm Computer.", system: "System", ankiWebSync: "AnkiWeb-Synchronisierig", syncing: "Anki und AnkiWeb werded synchronisiert …", syncComplete: "Synchronisierig abgschlosse.", syncFailed: "Synchronisierig fehlgschlage.", syncReady: "Manuell synchronisiere oder d Automatik bruuche.", syncNow: "Jetzt synchronisiere",
  translateType: "Übersetze und iitippe", speakTranslate: "Rede und übersetze", readUnderstand: "Lese und verstah", listening: "Hörverständnis", verbs: "Verbe", phonetics: "Ussproch", sounds: "Lüüt und Ussproch", characters: "Schriftzeiche", mnemonic: "Merksatz", enterJyutping: "Jyutping iitippe", frenchAnswer: "Französischi Antwort", withArticle: "Mit Artikel", phoneme: "Phonem",
};

const dictionaries: Record<UiLanguage, Record<string, string>> = { german: de, finnish: de, swiss: gsw, french: fr, cantonese: yue };
const locales: Record<UiLanguage, string> = { german: "de-CH", finnish: "fi-FI", swiss: "de-CH", french: "fr-CH", cantonese: "en-HK" };

export function createUi(language: UiLanguage) {
  const dictionary = dictionaries[language];
  const t: Translator = (key, values = {}) => {
    let value = dictionary[key] ?? de[key] ?? key;
    for (const [name, replacement] of Object.entries(values)) value = value.replaceAll(`{${name}}`, String(replacement));
    return value;
  };
  return { t, locale: locales[language] };
}
